---
title: "Pie_Figures"
author: "Kendall Calhoun"
date: "3/20/2019"
output: html_document
---
Using USGS data

```{r}
library(splitstackshape)
library(tidyverse)
library(ggplot2)
library(scales)
```

```{r}
fhist<-read_csv("data/landcover_fires_USGS.csv")
landclass <- read_csv("data/USGS_key.csv")
structures<- read_csv("data/structures_cost_calfire.csv")

structures<-structures %>%
  group_by(FIRE_NAME, YEAR) %>%
 summarise(structures_destroyed = mean(STRUCTURES_DEST),
           cost = mean(COST),
           DEATHS = mean(DEATHS)) %>%
 filter(cost>10)

#separate at =
fh <- fhist %>%
  cSplit("histogram", sep = ",", direction = "long") %>%
  cSplit("histogram", sep = "=", direction = "wide") %>%
  left_join(landclass) 

#Remove dupplicates (Thomas Fire, Ranch Fire, Biscuit Fire)

#Remove duplicate THOMAS 2017 fire
fh <- fh %>%
  filter(., FIRE_NAME != "THOMAS" | AGENCY != "C&L")

#Remove duplicate RANCH 2018 fire
fh <- fh %>%
  filter(.,FIRE_NAME != "RANCH" | MAPMETHOD != "Mixed Methods")
#Remove Biscuit Fire (Most of fire occurs in Oregon)
fh <- fh %>%
  filter(., FIRE_NAME != "BISCUIT")

usgs_landcover_fire<- fh %>%
  group_by(Landcover) %>%
  summarise(area = sum(histogram_2) *0.078 *2.47105) %>%
  na.omit() %>%
  ggplot(aes(x=Landcover, y= area )) +
  geom_bar(stat="identity") + coord_flip()
usgs_landcover_fire

catagory_fire<- fh %>%
  group_by(Category) %>%
  summarise(area = sum(histogram_2) *0.078 *2.47105) %>%
  na.omit() %>%
  ggplot(aes(x=Category, y= area )) +
  geom_bar(stat="identity") + coord_flip()
catagory_fire

fire_perc<- fh %>%  
  mutate(YEARn = as.numeric(YEAR)) %>%
  filter(YEARn>30,
         GIS_ACRES>75000) %>%
  group_by(FIRE_NAME, Category, GIS_ACRES, YEARn) %>%
  left_join(structures) %>%
  summarise(area = sum(histogram_2)) %>%
  mutate(area = area * .078 * 2.47) %>%
  na.omit() 

fire_perc_all <- fh %>%  
  mutate(YEARn = as.numeric(YEAR)) %>%
  group_by(FIRE_NAME, Category, GIS_ACRES, YEARn) %>%
  left_join(structures) %>%
  summarise(area = sum(histogram_2)) %>%
  mutate(area = area * .078 * 2.47) %>%
  na.omit() 

cols <- c("Forest" = "darkgreen", "Grassland" = "#799479", "Shrub" = "#DBA901", "Urban/Agriculture" = "gray") 

cols <- c("Forest" = "darkgreen", 
          "Grassland" = "#A0522D", 
          "Shrub" = "#DEB887", 
          "Urban/Agriculture" = "gray") 

fire_perc$Category<-factor(fire_perc$Category, levels=c('Urban/Agriculture', 
                                                           'Grassland',
                                                           'Shrub',
                                                           'Forest'))

fire_perc_all$Category <- factor(fire_perc_all$Category, levels=c('Urban/Agriculture', 
                                                           'Grassland',
                                                           'Shrub',
                                                           'Forest'))
```
#Pie Part!

```{r}
#Blank themee

cols <- c("Forest" = "darkgreen", 
          "Grassland" = "#e4d547",
          "Shrub" = "#fea201", 
          "Urban/Agriculture" = "gray") 
blank_theme <- theme_minimal()+
  theme(
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  panel.border = element_blank(),
  panel.grid=element_blank(),
  axis.ticks = element_blank(),
  plot.title=element_text(size=14, face="bold"))

#Composition of structures destroyed
top_structures_dest <- read_csv("data/top_struct_dest_2000_2018.csv")

destructive_fires <- c(top_structures_dest$name)

destructive <- fire_perc_all %>%
  filter(., FIRE_NAME %in% destructive_fires)

destructive <- destructive %>%
  filter(FIRE_NAME != "CEDAR" | YEARn != 2016)

strucutres_bar <- destructive %>%
  ggplot(aes(x = "Destructive Fires Veg Cover", y = area, fill = Category)) + 
  geom_bar(width = 1, stat = "identity") +
  scale_colour_manual(values = cols, aesthetics = c("colour", "fill")) + 
  theme_minimal() +
  theme(legend.title=element_blank())
strucutres_bar

strucutres_pie <- strucutres_bar + coord_polar("y", start=0)
strucutres_pie

#now one for all the fires

all_fires_bar <- fire_perc_all %>%
  ggplot(aes(x = "All Fires Burned Veg Cover", y = area, fill = Category)) + 
  geom_bar(width = 1, stat = "identity") +
  scale_colour_manual(values = cols, aesthetics = c("colour", "fill")) + 
  theme_minimal() +
  theme(legend.title=element_blank())
          
all_fires_bar

all_fires_pie <- all_fires_bar + coord_polar("y", start=0) + blank_theme + 
  theme(axis.text.x=element_blank())

all_fires_pie
strucutres_pie

#Megafire pie chart

megafire_perc <- fire_perc2 %>%
  filter(GIS_ACRES >= 100000)

megafire_bar <- megafire_perc %>%
  ggplot(aes(x = "Megafires Veg Cover", y = area, fill = Category)) + 
  geom_bar(width = 1, stat = "identity") +
  scale_colour_manual(values = cols, aesthetics = c("colour", "fill")) + 
  theme_minimal() +
  theme(legend.title=element_blank())
megafire_bar

megafire_pie <-megafire_bar + coord_polar("y", start=0) + theme(axis.text.x=element_blank()) + blank_theme

megafire_pie
all_fires_pie
strucutres_pie
```

Prettier Pies

```{r}
allfire_wedges <- aggregate(fire_perc2$area, by=list(Category=fire_perc2$Category), FUN=sum)
allfire_wedges
colnames(allfire_wedges) <- c("Category", "area")

structure_wedges <- aggregate(destructive$area, by=list(Category=destructive$Category), FUN=sum)
structure_wedges
colnames(structure_wedges) <- c("Category", "area")

megafire_wedges <- aggregate(megafire_perc$area, by=list(Category=megafire_perc$Category), FUN=sum)
megafire_wedges

allfires_wedgebar <- allfire_wedges %>%
  ggplot(aes(x = "", y = area, fill = Category)) + 
  geom_bar(width = 1, stat = "identity") +
  scale_colour_manual(values = cols, aesthetics = c("colour", "fill")) + 
  theme_minimal() +
  theme(legend.title=element_blank())
allfires_wedgebar

allfires_pie_wedge <- allfires_wedgebar + coord_polar("y", start=0) + blank_theme + 
  theme(axis.text.x=element_blank()) +
  ggtitle("Veg Cover of All Fires (>10,000 acres)") +
  theme(plot.title = element_text(size = 15, family = "Helvetica", face = "bold")) +
  theme(legend.text=element_text(size=8, family = "Helvetica"))
allfires_pie_wedge

str_bar <- structure_wedges %>%
  ggplot(aes(x = "", y = area, fill = Category)) + 
  geom_bar(width = 1, stat = "identity") +
  scale_colour_manual(values = cols, aesthetics = c("colour", "fill")) + 
  theme_minimal() +
  theme(legend.title=element_blank())
  
str_bar

str_pie <- str_bar +  coord_polar("y", start=0) + blank_theme + 
  theme(axis.text.x=element_blank()) +
  ggtitle("Veg Cover of Most Destructive Fires (structures)") +
  theme(plot.title = element_text(size = 15, family = "Helvetica", face = "bold")) +
  theme(legend.text=element_text(size=8, family = "Helvetica"))
str_pie
allfires_pie_wedge
```
Most destructive fires are taken from Calfire "Top 20 Most Destructive Fires of CA" only looking at fires 2000-2018. 15 of the 20 fires are within this time period.

All fires now reflects ALL the fires, not just fire >75,000 acres